Repository wp-cli/role-command, pull requests merged in 2018-04, with the labels that each got.

#20 Raise memory limit to 2048MB
  .travis.yml
Labels: bug, scope:testing

#19 add --show-grant argument to wp cap list and --grant to wp cap add
  features/cap.feature
  src/Capabilities_Command.php
Labels: command:cap-add, command:cap-list

#21 Update scaffolded files
  .gitignore
  README.md
  bin/test.sh
  features/bootstrap/FeatureContext.php
  features/bootstrap/Process.php
  features/bootstrap/utils.php
  utils/behat-tags.php
Labels: scope:testing
