Repository wp-cli/role-command, pull requests merged in 2019-04, with the labels that each got.

#30 Move PHP 5.4 tests from `WP_VERSION` `latest` to `5.1`
  .travis.yml
Labels: scope:distribution

#32 Enhancement: Add PHP 7.3 to Travis CI build matrix
  .travis.yml
Labels: scope:testing

#33 Implement CS checking based on the `WP_CLI_CS` ruleset
  .distignore
  .gitignore
  composer.json
  phpcs.xml.dist
  role-command.php
  src/Capabilities_Command.php
  src/Role_Command.php
Labels: command:cap, command:role

#34 Update README.md file
  README.md
Labels: scope:documentation
