Repository wp-cli/role-command, pull requests merged in 2023-02, with the labels that each got.

#54 Replace empty namespace autoloader with classmap
  composer.json
Labels: scope:distribution

#55 Add `composer phpcbf` and allow `wordpress-core-installer`
  composer.json
Labels: scope:testing

#58 Add explanation of what happens for `wp role reset`
  README.md
  src/Role_Command.php
Labels: scope:documentation
